/*
 * File:   GPIO Mapping.h
 *
 * Sets the pins between Frankenstein and NIRscan Nano
 *
 * Copyright (C) 2014-2015 Texas Instruments Incorporated - http://www.ti.com
 * ALL RIGHTS RESERVED
 *
 */

#ifndef GPIO_MAPPING_H_
#define GPIO_MAPPING_H_

#define NIRSCAN_NANO
 
// NIRscan Nano GPIO port definitions

#ifdef NIRSCAN_NANO

/* Comment Format:
 *
 * // Pin-Number => Descripion (Schematic Net) [Connector/Button]
 * 
 * If there is no net name or board connector/button, these are omitted
 */

#ifdef GREEN_LED_TIVA_BOARD
// PF5 => Green LED [D3]
#define GREEN_GPIO_PORT		GPIO_PORTF_AHB_DATA_R
#define GREEN_GPIO_MASK		GPIO_PIN_5
#endif
#ifdef GREEN_LED_EXP_CONN
// PA5 => Green LED [J3 pin 6]
#define GREEN_GPIO_PORT		GPIO_PORTA_AHB_DATA_R
#define GREEN_GPIO_MASK		GPIO_PIN_5
#endif

#ifdef YELLOW_LED_TIVA_BOARD
// PL4 => Yellow LED [D1]
#define YELLOW_GPIO_PORT	GPIO_PORTL_DATA_R
#define YELLOW_GPIO_MASK	GPIO_PIN_4
#endif
#ifdef YELLOW_LED_EXP_CONN
// PA4 => Yellow LED [J3 pin 5]
#define YELLOW_GPIO_PORT	GPIO_PORTA_AHB_DATA_R
#define YELLOW_GPIO_MASK	GPIO_PIN_4
#endif

#ifdef BLUE_LED_TIVA_BOARD
// PH7 => Blue LED [D2]
#define BLUE_GPIO_PORT		GPIO_PORTH_AHB_DATA_R
#define BLUE_GPIO_MASK		GPIO_PIN_7
#endif
#ifdef BLUE_LED_EXP_CONN
// PK7 => Blue LED [J3 pin 7]
#define BLUE_GPIO_PORT		GPIO_PORTK_DATA_R
#define BLUE_GPIO_MASK		GPIO_PIN_2
#endif

#ifdef SCAN_BUTTON_TIVA_BOARD
// PQ3 => Scan button (SW_SCAN) [SW1]
#define SCAN_ICR			GPIO_PORTQ_ICR_R
#define SCAN_GPIO_PORT		GPIO_PORTQ_DIR_R
#define SCAN_GPIO_EN		GPIO_PORTQ_DEN_R
#define SCAN_GPIO_IM		GPIO_PORTQ_IM_R
#define SCAN_GPIO_MASK		GPIO_PIN_3
#define SCAN_GPIO_SYSCTL	SYSCTL_PERIPH_GPIOQ
#endif
#ifdef SCAN_BUTTON_EXP_CONN
// PK3 => Scan button (SW_SCAN) [SW1]
#define SCAN_ICR			GPIO_PORTK_ICR_R
#define SCAN_RIS			GPIO_PORTK_RIS_R
#define SCAN_GPIO_PORT		GPIO_PORTK_DIR_R
#define SCAN_GPIO_EN		GPIO_PORTK_DEN_R
#define SCAN_GPIO_IM		GPIO_PORTK_IM_R
#define SCAN_GPIO_MASK		GPIO_PIN_3
#define SCAN_GPIO_SYSCTL	SYSCTL_PERIPH_GPIOK
#endif

// PD2 => Lamp Enable (TIVA_EXP_I2C_SCL) [J5]
#define LAMP_GPIO_PORT      GPIO_PORTD_BASE
#define LAMP_GPIO_MASK      GPIO_PIN_2

// PP2 => ADS1255 Data Ready (DRDYZ) [J2]
#define DRDY_GPIO_PORT  	GPIO_PORTP_DATA_R 
#define DRDY_GPIO_PORT_BASE GPIO_PORTP_BASE 
#define DRDY_GPIO_MASK     	GPIO_PIN_2
#define DRDY_GPIO_DIR		GPIO_PORTP_DIR_R
#define DRDY_GPIO_DEN		GPIO_PORTP_DEN_R
#define DRDY_GPIO_SYSCTL	SYSCTL_PERIPH_GPIOP

// PP7 => HDC1000 Data Ready (HUM_DRDYz)
#define HDC_DRDY_GPIO_PORT  GPIO_PORTP_DATA_R 
#define HDC_DRDY_GPIO_MASK  GPIO_PIN_7

// PH6 => ADS1255 SYNC (SYNCZ) [J2]
#define SYNC_GPIO_PORT  	GPIO_PORTH_AHB_DATA_R
#define SYNC_GPIO_PORT_BASE	GPIO_PORTH_BASE
#define SYNC_GPIO_MASK     	GPIO_PIN_6
#define SYNC_GPIO_DIR		GPIO_PORTH_AHB_DIR_R
#define SYNC_GPIO_DEN		GPIO_PORTH_AHB_DEN_R
#define SYNC_GPIO_SYSCTL	SYSCTL_PERIPH_GPIOH

// SS1 => Detector Serial Port [J2]
#define DET_SSI_BASE		SSI1_BASE
#define DET_SSI_SYSCTL		SYSCTL_PERIPH_SSI1
#define DET_SSI_DATA		SYSCTL_PERIPH_GPIOE
#define DET_SSI_CTL			SYSCTL_PERIPH_GPIOB
#define DET_SSI_CLK			GPIO_PB5_SSI1CLK
#define DET_SSI_FSS			GPIO_PB4_SSI1FSS
#define DET_SSI_DAT0		GPIO_PE4_SSI1XDAT0
#define DET_SSI_DAT1		GPIO_PE5_SSI1XDAT1
#define DET_GPIO_PORT_DATA	GPIO_PORTE_BASE
#define DET_GPIO_PORT_CTL	GPIO_PORTB_BASE
#define DET_GPIO_CLK		GPIO_PIN_5
#define DET_GPIO_CS			GPIO_PIN_4
#define DET_GPIO_DIN		GPIO_PIN_5
#define DET_GPIO_DOUT		GPIO_PIN_4

// PE0 => LCD Data Enable Mask (TIVA_DATAEN_MASK)
#define DATAEN_GPIO_PORT  	GPIO_PORTE_BASE
#define DATAEN_GPIO_MASK    GPIO_PIN_0

// PE1 => LCD VSYNC Mask (TIVA_VSYNC_MASK)
#define VSYNC_GPIO_PORT  	GPIO_PORTE_BASE
#define VSYNC_GPIO_MASK    	GPIO_PIN_1

// LCD (PDATA_##) [J5]
#define LCD_GPIO_F			GPIO_PIN_7
#define LCD_GPIO_J			GPIO_PIN_2 | GPIO_PIN_3 | GPIO_PIN_4 | GPIO_PIN_5 | GPIO_PIN_6
#define LCD_GPIO_N			GPIO_PIN_6 | GPIO_PIN_7
#define LCD_GPIO_R    		GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3 | GPIO_PIN_4 | GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7
#define LCD_GPIO_S			GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3 | GPIO_PIN_4 | GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7
#define LCD_GPIO_T			GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3

#define LCD_4B_GPIO_F		GPIO_PIN_7
#define LCD_4B_GPIO_J		GPIO_PIN_6
#define LCD_4B_GPIO_N		0
#define LCD_4B_GPIO_R    	GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3 | GPIO_PIN_4 | GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7
#define LCD_4B_GPIO_S		GPIO_PIN_4 | GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7
#define LCD_4B_GPIO_T		GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2

// PP0 => DLPC150 Output Trigger 0 (DLPC_XLAT0_TIVA) [J5]
#define TRIG0_GPIO_ICR		GPIO_PORTP_ICR_R
#define TRIG0_GPIO_PORT		GPIO_PORTP_DATA_R
#define TRIG0_GPIO_MASK		GPIO_PIN_0
#define TRIG0_GPIO_SYSCTL	SYSCTL_PERIPH_GPIOP

// PP1 => DLPC150 Output Trigger 1 (DLPC_XLAT1_TIVA) [J5]
#define TRIG1_GPIO_ICR		GPIO_PORTP_ICR_R
#define TRIG1_GPIO_PORT		GPIO_PORTP_DATA_R
#define TRIG1_GPIO_MASK		GPIO_PIN_1
#define TRIG1_GPIO_SYSCTL	SYSCTL_PERIPH_GPIOP

// PD3 => Trigger to DLPC150 for pattern change (TIVA_EXP_I2C_SDA / DLPC150 TRIG_IN) [J5]
#define TRIGNEXT_GPIO_ICR		GPIO_PORTD_ICR_R
#define TRIGNEXT_GPIO_PORT		GPIO_PORTD_DATA_R
#define TRIGNEXT_GPIO_MASK		GPIO_PIN_3
#define TRIGNEXT_GPIO_SYSCTL	SYSCTL_PERIPH_GPIOD
#define TRIGNEXT_GPIO_PORT_BASE GPIO_PORTD_BASE

// UART4 => Console [J3]
#define CONSOLE_GPIO_SYSCTL	SYSCTL_PERIPH_GPIOA
#define CONSOLE_GPIO_RX		GPIO_PA2_U4RX
#define CONSOLE_GPIO_TX		GPIO_PA3_U4TX
#define CONSOLE_GPIO_RTS	GPIO_PK2_U4RTS
#define CONSOLE_GPIO_CTS	GPIO_PK3_U4CTS
#define CONSOLE_GPIO_BASE	GPIO_PORTA_BASE
#define CONSOLE_GPIO_PINS	GPIO_PIN_2 | GPIO_PIN_3
#define CONSOLE_GPIO_HS_BASE GPIO_PORTK_BASE
#define CONSOLE_GPIO_HS_PINS GPIO_PIN_2 | GPIO_PIN_3
#define CONSOLE_UART_BASE	UART4_BASE
#define CONSOLE_UART_SYSCTL	SYSCTL_PERIPH_UART4
#define CONSOLE_UART		4

#endif



// Frankenstein GPIO port definitions
#ifdef FRANKESTEIN

// PF5 => Green LED
#define GREEN_GPIO_PORT		GPIO_PORTF_AHB_DATA_R
#define GREEN_GPIO_MASK		GPIO_PIN_5

// PP1 => Select button
#define SCAN_ICR			GPIO_PORTP_ICR_R
#define SCAN_GPIO_PORT		GPIO_PORTP_DIR_R
#define SCAN_GPIO_EN		GPIO_PORTP_DEN_R
#define SCAN_GPIO_IM		GPIO_PORTP_IM_R
#define MASK_GPIO_SCAN		GPIO_PIN_1
#define SCAN_GPIO_SYSCTL	SYSCTL_PERIPH_GPIOP

// PH4 => ADS1255 DRDY
#define DRDY_GPIO_PORT  	GPIO_PORTH_AHB_DATA_R 
#define DRDY_GPIO_MASK     	GPIO_PIN_4
#define DRDY_GPIO_DIR		GPIO_PORTH_AHB_DIR_R
#define DRDY_GPIO_SYSCTL	SYSCTL_PERIPH_GPIOH


// PH6 => ADS1255 SYNC
#define SYNC_GPIO_PORT  	GPIO_PORTH_AHB_DATA_R 
#define SYNC_GPIO_MASK     	GPIO_PIN_6
#define SYNC_GPIO_DIR		GPIO_PORTH_AHB_DIR_R
#define SYNC_GPIO_DEN		GPIO_PORTH_AHB_DEN_R
#define SYNC_GPIO_SYSCTL	SYSCTL_PERIPH_GPIOH

// SS1 => Detector Serial Port
#define DET_SSI_BASE		SSI1_BASE
#define DET_SSI_SYSCTL		SYSCTL_PERIPH_SSI1
#define DET_SSI_DATA		SYSCTL_PERIPH_GPIOE
#define DET_SSI_CTL			SYSCTL_PERIPH_GPIOB
#define DET_SSI_CLK			GPIO_PB5_SSI1CLK
#define DET_SSI_FSS			GPIO_PB4_SSI1FSS
#define DET_SSI_DAT0		GPIO_PE4_SSI1XDAT0
#define DET_SSI_DAT1		GPIO_PE5_SSI1XDAT1
#define DET_GPIO_PORT_DATA	GPIO_PORTE_BASE
#define DET_GPIO_PORT_CTL	GPIO_PORTB_BASE
#define DET_GPIO_CLK		GPIO_PIN_4
#define DET_GPIO_CS			GPIO_PIN_5
#define DET_GPIO_DIN		GPIO_PIN_5
#define DET_GPIO_DOUT		GPIO_PIN_4

// LCD
#define LCD_GPIO_F			GPIO_PIN_7
#define LCD_GPIO_J			GPIO_PIN_2 | GPIO_PIN_3 | GPIO_PIN_4 | GPIO_PIN_5 | GPIO_PIN_6
#define LCD_GPIO_N			GPIO_PIN_6 | GPIO_PIN_7
#define LCD_GPIO_R    		GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3 | GPIO_PIN_4 | GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7
#define LCD_GPIO_S			GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3 | GPIO_PIN_4 | GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7
#define LCD_GPIO_T			GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3

#define LCD_4B_GPIO_F		GPIO_PIN_7
#define LCD_4B_GPIO_J		GPIO_PIN_6
#define LCD_4B_GPIO_N		0
#define LCD_4B_GPIO_R    	GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3 | GPIO_PIN_4 | GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7
#define LCD_4B_GPIO_S		GPIO_PIN_4 | GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7
#define LCD_4B_GPIO_T		GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2

// PN3 => Trigger monitor
#define TRIGMON_GPIO_PORT	GPIO_PORTN_DATA_R
#define TRIGMON_GPIO_MASK	GPIO_PIN_3
#define TRIGMON_GPIO_SYSCTL	SYSCTL_PERIPH_GPION

// PP1 => Trigger 
#define TRIG1_GPIO_PORT		GPIO_PORTP_DATA_R
#define TRIG1_GPIO_MASK		GPIO_PIN_1
#define TRIG1_GPIO_SYSCTL	SYSCTL_PERIPH_GPIOP

// UART0 => console
#define CONSOLE_GPIO_SYSCTL	SYSCTL_PERIPH_GPIOA
#define CONSOLE_GPIO_RX		GPIO_PA0_U0RX
#define CONSOLE_GPIO_TX		GPIO_PA1_U0TX
#define CONSOLE_GPIO_BASE	GPIO_PORTA_BASE
#define CONSOLE_GPIO_PINS	GPIO_PIN_0 | GPIO_PIN_1
#define CONSOLE_UART_BASE	UART0_BASE
#define CONSOLE_UART_SYSCTL	SYSCTL_PERIPH_UART0
#define CONSOLE_UART		0
#endif



#endif /* GPIO_MAPPING_H_ */
