################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
App/bleCmdHandler.obj: ../App/bleCmdHandler.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Common/include" --include_path="C:/Users/weiwei/workspace_v6_2/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.3/src" --include_path="C:/ti/TivaWare_C_Series-2.1.0.12573" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Drivers/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Board/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpsvend" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btvs/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="App/bleCmdHandler.d" --obj_directory="App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

App/button.obj: ../App/button.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Common/include" --include_path="C:/Users/weiwei/workspace_v6_2/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.3/src" --include_path="C:/ti/TivaWare_C_Series-2.1.0.12573" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Drivers/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Board/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpsvend" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btvs/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="App/button.d" --obj_directory="App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

App/cmdDict.obj: ../App/cmdDict.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Common/include" --include_path="C:/Users/weiwei/workspace_v6_2/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.3/src" --include_path="C:/ti/TivaWare_C_Series-2.1.0.12573" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Drivers/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Board/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpsvend" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btvs/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="App/cmdDict.d" --obj_directory="App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

App/cmdHandlerIFMgr.obj: ../App/cmdHandlerIFMgr.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Common/include" --include_path="C:/Users/weiwei/workspace_v6_2/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.3/src" --include_path="C:/ti/TivaWare_C_Series-2.1.0.12573" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Drivers/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Board/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpsvend" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btvs/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="App/cmdHandlerIFMgr.d" --obj_directory="App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

App/cmdProc.obj: ../App/cmdProc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Common/include" --include_path="C:/Users/weiwei/workspace_v6_2/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.3/src" --include_path="C:/ti/TivaWare_C_Series-2.1.0.12573" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Drivers/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Board/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpsvend" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btvs/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="App/cmdProc.d" --obj_directory="App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

App/display.obj: ../App/display.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Common/include" --include_path="C:/Users/weiwei/workspace_v6_2/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.3/src" --include_path="C:/ti/TivaWare_C_Series-2.1.0.12573" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Drivers/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Board/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpsvend" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btvs/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="App/display.d" --obj_directory="App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

App/main.obj: ../App/main.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Common/include" --include_path="C:/Users/weiwei/workspace_v6_2/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.3/src" --include_path="C:/ti/TivaWare_C_Series-2.1.0.12573" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Drivers/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Board/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpsvend" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btvs/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="App/main.d" --obj_directory="App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

App/nano_eeprom.obj: ../App/nano_eeprom.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Common/include" --include_path="C:/Users/weiwei/workspace_v6_2/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.3/src" --include_path="C:/ti/TivaWare_C_Series-2.1.0.12573" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Drivers/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Board/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpsvend" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btvs/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="App/nano_eeprom.d" --obj_directory="App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

App/nano_timer.obj: ../App/nano_timer.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Common/include" --include_path="C:/Users/weiwei/workspace_v6_2/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.3/src" --include_path="C:/ti/TivaWare_C_Series-2.1.0.12573" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Drivers/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Board/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpsvend" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btvs/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="App/nano_timer.d" --obj_directory="App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

App/nnoStatus.obj: ../App/nnoStatus.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Common/include" --include_path="C:/Users/weiwei/workspace_v6_2/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.3/src" --include_path="C:/ti/TivaWare_C_Series-2.1.0.12573" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Drivers/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Board/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpsvend" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btvs/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="App/nnoStatus.d" --obj_directory="App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

App/scan.obj: ../App/scan.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Common/include" --include_path="C:/Users/weiwei/workspace_v6_2/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.3/src" --include_path="C:/ti/TivaWare_C_Series-2.1.0.12573" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Drivers/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Board/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpsvend" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btvs/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="App/scan.d" --obj_directory="App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

App/trigger.obj: ../App/trigger.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Common/include" --include_path="C:/Users/weiwei/workspace_v6_2/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.3/src" --include_path="C:/ti/TivaWare_C_Series-2.1.0.12573" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Drivers/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Board/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpsvend" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btvs/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="App/trigger.d" --obj_directory="App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

App/uartCmdHandler.obj: ../App/uartCmdHandler.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Common/include" --include_path="C:/Users/weiwei/workspace_v6_2/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.3/src" --include_path="C:/ti/TivaWare_C_Series-2.1.0.12573" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Drivers/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Board/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpsvend" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btvs/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="App/uartCmdHandler.d" --obj_directory="App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

App/usbCmdHandler.obj: ../App/usbCmdHandler.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Common/include" --include_path="C:/Users/weiwei/workspace_v6_2/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.3/src" --include_path="C:/ti/TivaWare_C_Series-2.1.0.12573" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Drivers/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Board/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpsvend" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btvs/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="App/usbCmdHandler.d" --obj_directory="App" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


