################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
BLE/Bluetopia/btpsvend/BTPSVEND.obj: ../BLE/Bluetopia/btpsvend/BTPSVEND.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 --abi=eabi -me -Ooff --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.9/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Common/include" --include_path="C:/Users/weiwei/workspace_v6_2/Common/include" --include_path="C:/ti/DLPSpectrumLibrary_2.0.3/src" --include_path="C:/ti/TivaWare_C_Series-2.1.0.12573" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Drivers/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/Board/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpskrnl/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btpsvend" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/btvs/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/App/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gatt/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/gaps/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/hcitrans/TI_RTOS" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/bas/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/include" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Bluetopia/profiles/dis/source" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware" --include_path="C:/Users/weiwei/workspace_v6_2/MobileSpectroscopyTIVAEVM/BLE/Hardware/dk-tm4c129x" -g --relaxed_ansi --gcc --define=UART_BUFFERED --define=TARGET_IS_TM4C129_RA0 --define=ccs --define=TIVAWARE --define=DEBUG_USERINPUT_C --define=PART_TM4C129XNCZAD --define=DEBUG_ZONES=DBG_ZONE_ANY --define=__USE_TI_RTOS__ --define=__SUPPORT_LOW_ENERGY__ --define=ccs="ccs" --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="BLE/Bluetopia/btpsvend/BTPSVEND.d" --obj_directory="BLE/Bluetopia/btpsvend" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


